name: CI

permissions: {}

on:
  push:
    branches: ["main", "feat/**"]
  pull_request:
    branches: ["main"]
  workflow_dispatch:

env:
  FOUNDRY_PROFILE: ci
  MAINNET_RPC_URL: ${{ secrets.MAINNET_RPC_URL }}

jobs:
  check:
    name: Foundry project
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false
          submodules: recursive

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1

      - name: Show Forge version
        run: forge --version

      - name: Run Forge fmt
        run: forge fmt --check

      - name: solhint
        run: |
          npm install -g solhint
          solhint 'contracts/**/*.sol' --ignore-path .gitignore

      - name: Run Forge build
        run: forge build --sizes

      - name: forge test (unit, fuzz, invariant)
        run: forge test --no-match-path "test/fork/*" -vvv

      - name: forge test (fork)
        run: forge test --match-path "test/fork/*" --fork-url $MAINNET_RPC_URL -vvv
        env:
          MAINNET_RPC_URL: ${{ secrets.MAINNET_RPC_URL }}
 
      - name: forge coverage
        run: forge coverage --no-match-path "test/fork/*" --report summary
 
      - name: forge snapshot check
        run: forge snapshot --match-contract YulBenchmark --check
 
      - name: slither
        run: |
          pip3 install slither-analyzer
          slither contracts/ --exclude-dependencies --fail-on high || true
 
